# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userapi/user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='userapi/user.proto',
  package='io.netograph.user',
  syntax='proto3',
  serialized_options=b'Z\007userapi',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12userapi/user.proto\x12\x11io.netograph.user\x1a\x1fgoogle/protobuf/timestamp.proto\"&\n\x08Metadata\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x11\n\x0f\x44\x61tasetsRequest\"|\n\x07\x44\x61taset\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07urlbase\x18\x03 \x01(\t\x12+\n\x07\x64\x65leted\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08readonly\x18\x05 \x01(\x08\"\x83\x01\n\x12TempCaptureRequest\x12\x14\n\x0cnotification\x18\x01 \x01(\t\x12\x0c\n\x04urls\x18\x02 \x03(\t\x12)\n\x04meta\x18\x03 \x03(\x0b\x32\x1b.io.netograph.user.Metadata\x12\x0c\n\x04zone\x18\x04 \x01(\t\x12\x10\n\x08\x65xtended\x18\x05 \x01(\x08\"/\n\x11TempCaptureResult\x12\x0e\n\x06\x61ssets\x18\x01 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\"x\n\x07\x43\x61pture\x12\x14\n\x0cnotification\x18\x01 \x01(\t\x12\x0c\n\x04urls\x18\x02 \x03(\t\x12)\n\x04meta\x18\x03 \x03(\x0b\x32\x1b.io.netograph.user.Metadata\x12\x0c\n\x04zone\x18\x04 \x01(\t\x12\x10\n\x08\x65xtended\x18\x05 \x01(\x08\"+\n\rCaptureResult\x12\x0e\n\x06\x61ssets\x18\x01 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\">\n\x0e\x43\x61ptureRequest\x12,\n\x08\x63\x61ptures\x18\x01 \x03(\x0b\x32\x1a.io.netograph.user.Capture2\x82\x02\n\x04User\x12Z\n\x0bTempCapture\x12%.io.netograph.user.TempCaptureRequest\x1a$.io.netograph.user.TempCaptureResult\x12P\n\x07\x43\x61pture\x12!.io.netograph.user.CaptureRequest\x1a .io.netograph.user.CaptureResult0\x01\x12L\n\x08\x44\x61tasets\x12\".io.netograph.user.DatasetsRequest\x1a\x1a.io.netograph.user.Dataset0\x01\x42\tZ\x07userapib\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_METADATA = _descriptor.Descriptor(
  name='Metadata',
  full_name='io.netograph.user.Metadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='io.netograph.user.Metadata.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='io.netograph.user.Metadata.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=112,
)


_DATASETSREQUEST = _descriptor.Descriptor(
  name='DatasetsRequest',
  full_name='io.netograph.user.DatasetsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=131,
)


_DATASET = _descriptor.Descriptor(
  name='Dataset',
  full_name='io.netograph.user.Dataset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='io.netograph.user.Dataset.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='io.netograph.user.Dataset.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='urlbase', full_name='io.netograph.user.Dataset.urlbase', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deleted', full_name='io.netograph.user.Dataset.deleted', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='readonly', full_name='io.netograph.user.Dataset.readonly', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=257,
)


_TEMPCAPTUREREQUEST = _descriptor.Descriptor(
  name='TempCaptureRequest',
  full_name='io.netograph.user.TempCaptureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='notification', full_name='io.netograph.user.TempCaptureRequest.notification', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='urls', full_name='io.netograph.user.TempCaptureRequest.urls', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meta', full_name='io.netograph.user.TempCaptureRequest.meta', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zone', full_name='io.netograph.user.TempCaptureRequest.zone', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extended', full_name='io.netograph.user.TempCaptureRequest.extended', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=391,
)


_TEMPCAPTURERESULT = _descriptor.Descriptor(
  name='TempCaptureResult',
  full_name='io.netograph.user.TempCaptureResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='assets', full_name='io.netograph.user.TempCaptureResult.assets', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='io.netograph.user.TempCaptureResult.id', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=440,
)


_CAPTURE = _descriptor.Descriptor(
  name='Capture',
  full_name='io.netograph.user.Capture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='notification', full_name='io.netograph.user.Capture.notification', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='urls', full_name='io.netograph.user.Capture.urls', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meta', full_name='io.netograph.user.Capture.meta', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zone', full_name='io.netograph.user.Capture.zone', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extended', full_name='io.netograph.user.Capture.extended', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=562,
)


_CAPTURERESULT = _descriptor.Descriptor(
  name='CaptureResult',
  full_name='io.netograph.user.CaptureResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='assets', full_name='io.netograph.user.CaptureResult.assets', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='io.netograph.user.CaptureResult.id', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=564,
  serialized_end=607,
)


_CAPTUREREQUEST = _descriptor.Descriptor(
  name='CaptureRequest',
  full_name='io.netograph.user.CaptureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='captures', full_name='io.netograph.user.CaptureRequest.captures', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=609,
  serialized_end=671,
)

_DATASET.fields_by_name['deleted'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TEMPCAPTUREREQUEST.fields_by_name['meta'].message_type = _METADATA
_CAPTURE.fields_by_name['meta'].message_type = _METADATA
_CAPTUREREQUEST.fields_by_name['captures'].message_type = _CAPTURE
DESCRIPTOR.message_types_by_name['Metadata'] = _METADATA
DESCRIPTOR.message_types_by_name['DatasetsRequest'] = _DATASETSREQUEST
DESCRIPTOR.message_types_by_name['Dataset'] = _DATASET
DESCRIPTOR.message_types_by_name['TempCaptureRequest'] = _TEMPCAPTUREREQUEST
DESCRIPTOR.message_types_by_name['TempCaptureResult'] = _TEMPCAPTURERESULT
DESCRIPTOR.message_types_by_name['Capture'] = _CAPTURE
DESCRIPTOR.message_types_by_name['CaptureResult'] = _CAPTURERESULT
DESCRIPTOR.message_types_by_name['CaptureRequest'] = _CAPTUREREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Metadata = _reflection.GeneratedProtocolMessageType('Metadata', (_message.Message,), {
  'DESCRIPTOR' : _METADATA,
  '__module__' : 'userapi.user_pb2'
  # @@protoc_insertion_point(class_scope:io.netograph.user.Metadata)
  })
_sym_db.RegisterMessage(Metadata)

DatasetsRequest = _reflection.GeneratedProtocolMessageType('DatasetsRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATASETSREQUEST,
  '__module__' : 'userapi.user_pb2'
  # @@protoc_insertion_point(class_scope:io.netograph.user.DatasetsRequest)
  })
_sym_db.RegisterMessage(DatasetsRequest)

Dataset = _reflection.GeneratedProtocolMessageType('Dataset', (_message.Message,), {
  'DESCRIPTOR' : _DATASET,
  '__module__' : 'userapi.user_pb2'
  # @@protoc_insertion_point(class_scope:io.netograph.user.Dataset)
  })
_sym_db.RegisterMessage(Dataset)

TempCaptureRequest = _reflection.GeneratedProtocolMessageType('TempCaptureRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEMPCAPTUREREQUEST,
  '__module__' : 'userapi.user_pb2'
  # @@protoc_insertion_point(class_scope:io.netograph.user.TempCaptureRequest)
  })
_sym_db.RegisterMessage(TempCaptureRequest)

TempCaptureResult = _reflection.GeneratedProtocolMessageType('TempCaptureResult', (_message.Message,), {
  'DESCRIPTOR' : _TEMPCAPTURERESULT,
  '__module__' : 'userapi.user_pb2'
  # @@protoc_insertion_point(class_scope:io.netograph.user.TempCaptureResult)
  })
_sym_db.RegisterMessage(TempCaptureResult)

Capture = _reflection.GeneratedProtocolMessageType('Capture', (_message.Message,), {
  'DESCRIPTOR' : _CAPTURE,
  '__module__' : 'userapi.user_pb2'
  # @@protoc_insertion_point(class_scope:io.netograph.user.Capture)
  })
_sym_db.RegisterMessage(Capture)

CaptureResult = _reflection.GeneratedProtocolMessageType('CaptureResult', (_message.Message,), {
  'DESCRIPTOR' : _CAPTURERESULT,
  '__module__' : 'userapi.user_pb2'
  # @@protoc_insertion_point(class_scope:io.netograph.user.CaptureResult)
  })
_sym_db.RegisterMessage(CaptureResult)

CaptureRequest = _reflection.GeneratedProtocolMessageType('CaptureRequest', (_message.Message,), {
  'DESCRIPTOR' : _CAPTUREREQUEST,
  '__module__' : 'userapi.user_pb2'
  # @@protoc_insertion_point(class_scope:io.netograph.user.CaptureRequest)
  })
_sym_db.RegisterMessage(CaptureRequest)


DESCRIPTOR._options = None

_USER = _descriptor.ServiceDescriptor(
  name='User',
  full_name='io.netograph.user.User',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=674,
  serialized_end=932,
  methods=[
  _descriptor.MethodDescriptor(
    name='TempCapture',
    full_name='io.netograph.user.User.TempCapture',
    index=0,
    containing_service=None,
    input_type=_TEMPCAPTUREREQUEST,
    output_type=_TEMPCAPTURERESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Capture',
    full_name='io.netograph.user.User.Capture',
    index=1,
    containing_service=None,
    input_type=_CAPTUREREQUEST,
    output_type=_CAPTURERESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Datasets',
    full_name='io.netograph.user.User.Datasets',
    index=2,
    containing_service=None,
    input_type=_DATASETSREQUEST,
    output_type=_DATASET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USER)

DESCRIPTOR.services_by_name['User'] = _USER

# @@protoc_insertion_point(module_scope)
