#!/usr/bin/env python

# The Python GRPC compiler has trouble dealing correctly with Python3-style
# imports. We fix this in post, rather crudely for now.

SPATH = "netograph/ngapi_pb2_grpc.py"

f = open(SPATH).read().replace("import ngapi_pb2", "import netograph.ngapi_pb2")
out = open(SPATH, "w").write(f)
