#!/usr/bin/env python

# The Python GRPC compiler has trouble dealing correctly with Python3-style
# imports. We fix this in post, rather crudely for now.

SPATH = "netograph/dsetapi/dset_pb2_grpc.py"
f = open(SPATH).read().replace("from dsetapi", "from netograph.dsetapi")
out = open(SPATH, "w").write(f)

SPATH = "netograph/userapi/user_pb2_grpc.py"
f = open(SPATH).read().replace("from userapi", "from netograph.userapi")
out = open(SPATH, "w").write(f)
